export const ERROR_CODES = {
  INVALID_INPUT: 'INVALID_INPUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  HOST_EMAIL_NOT_VERIFIED: 'HOST_EMAIL_NOT_VERIFIED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  POLL_NOT_FOUND: 'POLL_NOT_FOUND',
  POLL_LOCKED: 'POLL_LOCKED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  CONFIRMATION_REQUIRED: 'CONFIRMATION_REQUIRED',
  NO_POLLS: 'NO_POLLS',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
